### ISSUE TITLE
Easier Install

### ISSUE THREAD

**Issue by gabe0x02** [ryanfitzer/eslint.tmbundle#1]
Thanks for this.  I like the tooltip feature better than other eslint bundles.

I found that If you just rename your release dir with a . tmbundle suffix TextMate will automatically install the bundle with a double click.

Cheers!

**Comment by ryanfitzer** [comment]
> Thanks for this. I like the tooltip feature better than other eslint bundles.

Glad you like it!

> I found that If you just rename your release dir with a . tmbundle suffix

I agree, but I don't see a way of doing that and still be able to use Github's automatic "Releases" feature. Do you know of a workaround?

**Comment by ryanfitzer** [comment]
Uploading the renamed `.zip` file is the best option I've found, so far: https://github.com/ryanfitzer/eslint.tmbundle/releases/tag/v1.5.4.

Leaving this open until I can find an automated solution.

**Comment by ryanfitzer** [comment]
Archiving repo and closing issue.
