### ISSUE TITLE
Eslint 8 Error: No CLIEngine found.

### ISSUE THREAD

**Issue by imakeinterfaces** [ryanfitzer/eslint.tmbundle#10]
I'm getting this error with eslint 8. I'm wondering if something in the output format has changed and if anyone has an idea what changed
<img width="591" alt="Screen Shot 2022-07-11 at 3 02 57 PM" src="https://user-images.githubusercontent.com/860921/178339135-64d5a01e-2cb4-41b9-9207-2adde1e58358.png">
.

**Comment by imakeinterfaces** [comment]
Unfortunately it looks like CLIEngine has been completely deprecated https://eslint.org/docs/latest/user-guide/migrating-to-8.0.0#remove-cliengine I started taking a look to see what would need to change.

**Comment by ryanfitzer** [comment]
I have not had time to work on keeping this up-to-date with ESLint's release schedule. But if you want to help, I can answer any questions you have about what is needed to update the bundle to be compatible with the most recent version.

I put in a lot of effort to keep the different parts/concerns as decoupled as possible so it would hopefully be easy to maintain. 

Let me know if you're interested and we can work together on a PR.

**Comment by ryanfitzer** [comment]
@imakeinterfaces The changes needed to support ESLint v8 were easier than I expected. Can you test the release and let me know if you run into any issues? [v2.0.0-beta](https://github.com/ryanfitzer/eslint.tmbundle/releases/tag/v2.0.0-beta)

**Comment by imakeinterfaces** [comment]
@ryanfitzer Thanks! I did a quick test locally and i'm getting the following error. I will try to look at it more later today.

```
/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 2.tmbundle/Support/index.js:163
    const { ESLint, SourceCode } = requireTry( eslintPath, TMconfig );
            ^

TypeError: Cannot destructure property 'ESLint' of 'requireTry(...)' as it is undefined.
    at module.exports (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 2.tmbundle/Support/index.js:163:13)
    at Lint:11:5
    at Socket.<anonymous> (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 2.tmbundle/Support/lib/read-input.js:9:36)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by imakeinterfaces** [comment]
Update: As a workaround, I set my TM_eslint_path var to /Users/sam/.nvm/versions/node/v16.15.1/bin/eslint
Now i get a new error.

```
Oops! Something went wrong! :(

ESLint: 8.19.0


TypeError: eslint is not a constructor
    at createCLI (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 2.tmbundle/Support/index.js:100:12)
    at module.exports (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 2.tmbundle/Support/index.js:164:17)
    at Lint:11:5
    at Socket.<anonymous> (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 2.tmbundle/Support/lib/read-input.js:9:36)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by ryanfitzer** [comment]
Is ESLint installed locally in your project?

**Comment by imakeinterfaces** [comment]
Sorry for the log dump. I got it working now on one project, but it had issues in another. I'll continue to use it and see what I find.

**Comment by ryanfitzer** [comment]
@imakeinterfaces I've published [release v2.0.0-beta-1](https://github.com/ryanfitzer/eslint.tmbundle/releases/tag/v2.0.0-beta-1) that adds more debug info.

Can you post a screenshot of the output from the **Debug** command?

Menu item:

![Screen Shot 2022-07-12 at 2 01 52 PM](https://user-images.githubusercontent.com/384629/178595098-c43e3884-1a7c-43f5-82fa-ea23271faa9f.png)

Example output:

![Screen Shot 2022-07-12 at 2 02 31 PM](https://user-images.githubusercontent.com/384629/178595169-ee1e394e-db0d-42d1-95c3-fc3ae44a0bb1.png)

**Comment by imakeinterfaces** [comment]
@ryanfitzer Thanks for that! Unfortunately in this app that's failing i'm getting a popup dialog with the following error:

```
/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 3.tmbundle/Support/index.js:135
            const leadSpace = msg.source.match( /^\s*/ );
                                         ^

TypeError: Cannot read properties of undefined (reading 'match')
    at /Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 3.tmbundle/Support/index.js:135:42
    at Array.map (<anonymous>)
    at composeData (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 3.tmbundle/Support/index.js:131:46)
    at module.exports (/Users/sam/Library/Application Support/TextMate/Pristine Copy/Bundles/ESLint 3.tmbundle/Support/index.js:229:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```



```
ESLint.tmbundle Debug

Node.js Version

16.16.0
Node.js Executable Path

/usr/local/bin/node
ESLint Module Path

/Users/sam/dev/xyz/node_modules/eslint
Environment Path

/usr/bin:/bin:/usr/sbin:/sbin:/Users/sam/Library/Application Support/TextMate/Managed/Bundles/Bundle Support.tmbundle/Support/shared/bin:/opt/local/bin:/usr/local/bin:/usr/texbin:/Users/sam/.nvm/versions/node/v16.15.1/bin
TMconfig

{
  "view": "window",
  "hrstart": [
    43929,
    506429083
  ],
  "TMdebug": true
}
ESLint v8.13.0 options

{
  "fix": false,
  "useEslintrc": true,
  "cwd": "/Users/sam/dev/xyz/lib/packages/page"
}

```

**Comment by ryanfitzer** [comment]
Are you able to create a minimal project that reproduces the issue?

**Comment by imakeinterfaces** [comment]
I seem to have figured it out, at least partially. If i check `msg.source` defensively on https://github.com/ryanfitzer/eslint.tmbundle/blob/master/Support/index.js#L141
and then again on line 148 i can see the error.

![Screen Shot 2022-07-12 at 10 23 10 PM](https://user-images.githubusercontent.com/860921/178639430-47c67544-6244-4a37-a5ec-1aa2065ee819.jpg)

I changed the lines to 
141: `const leadSpace = msg.source && msg.source.match( /^\s*/ );`
148: `msg.source = msg.source && msg.source.trim();`

Oddly, this project does have a babel.config.js file. I will keep looking into it

**Comment by ryanfitzer** [comment]
Thanks for keeping on this. I added your changes to [v2.0.0-beta-2](https://github.com/ryanfitzer/eslint.tmbundle/releases/tag/v2.0.0-beta-2). For line `148` I used a ternary so I didn't affect the value of `msg.source` when it's falsey.

Not sure why that Babel plugin error is happening. Is your `eslint-plugin-babel` up-to-date? Or is there some other ESLint Babel plugin that might be affecting it?

Also, your `PATH` output shows a direct link to a specific Node.js version:

```
/Users/sam/.nvm/versions/node/v16.15.1/bin
```

But the actual executable being used by Textmate shows as:

```
/usr/local/bin/node
```

Not sure this has any relationship to the issue (they are both v16.x), but you might not be expecting this.

Do you see anything else that would need to be done before I release this? I'm happy to test it out on a minimal example, if you have one.

**Comment by ryanfitzer** [comment]
Archiving repo and closing issue.
