### ISSUE TITLE
Return focus to editing window after `lint` is run

### ISSUE THREAD

**Issue by imakeinterfaces** [ryanfitzer/eslint.tmbundle#8]
Currently running the lint command with the html based error list moves the window focus from the editor to the html preview/error window. This is mostly a problem if you show the html output in the same window as the editor since the cursor position is constantly lost.

**Comment by ryanfitzer** [comment]
I always show the output in a new window, so I’ve never run into this issue. I’ll let you know if I have any issues reproducing it.

**Comment by ryanfitzer** [comment]
@imakeinterfaces Just took a look. This behavior is not something that is controlled by Textmate, not at the bundle. At a minimum, I expect it's for accessibility.

When your preference for **Show command output** is set to something other than "New window", you can return to the document with the shortcut `⌥ ⌘ ⇥`

(**Edit**: You can also use the shortcut `⌘ w` to close the window)

Not the greatest option, but I'm not sure how Textmate would be accessible if it didn't focus the output each time (I could be wrong on this).

While not documented, you can press the number associated with an ESLint error in the output, and it will focus your cursor to that position in the document.

With that said, I think I can give the option for setting focus back to the document when no errors/warnings are present in the output. This would require your project to have a `.tm_properties` file (or a global one). Is that something you'd be interested in?

**Comment by imakeinterfaces** [comment]
@ryanfitzer Thank you for looking into this. Good to know about ⌥ ⌘ ⇥ and the number trick. Both of those are very useful. I'm not sure if its worth changing the behavior when there are no errors as it seems like the inconsistency might get frustrating. Also, I imagine this would be difficult as the HTML view still needs to be updated in order to remove the errors from it and this will of course cause a refocus.

The way I use this bundle is to run this command on save. It really is a great way to use autoformat with something like prettier. I'll probably continue to use this bundle forever even with this problem.

**Comment by ryanfitzer** [comment]
> The way I use this bundle is to run this command on save.

Does the "Lint on Save" command (shows a tooltip on save whenever errors are found) not do what you need?

I'm also looking into the [`autoRefresh`](https://github.com/textmate/textmate/blob/master/Applications/TextMate/about/Changes.md#2016-10-03-v20-beta1221) feature. In my testing, it updates the HTML output without refocusing the window. But for some reason, once I close the window, running the "Lint" command refuses to reopen it.

If I can get it to work reliably, I add it as another command. I think this should give you the behavior you were originally looking for.

> I'll probably continue to use this bundle forever even with this problem.

Awesome! Glad it's helpful.

**Comment by ryanfitzer** [comment]
I've add an experimental auto-refresh command "Enable Live Lint" (see the ["Experimental" section](https://github.com/ryanfitzer/eslint.tmbundle/tree/v1.6.0#commands) for more details).

Please give [v1.6.0 a try](https://github.com/ryanfitzer/eslint.tmbundle/releases/download/v1.6.0/eslint.tmbundle.zip) and let me know if you find any issues.

**Comment by imakeinterfaces** [comment]
@ryanfitzer I just started using this today and its awesome! One thing I did notice though is that the autofixer seems to be missing from the command now so that i can't use autoformat. Maybe I'm doing something wrong, i'm not sure.

**Comment by imakeinterfaces** [comment]
@ryanfitzer Ignore that last comment, i just needed to set TM_eslint_fix=true. I might have patched my own bundle to always use this at some point. Everything works great now. Thanks so much for this extremely useful feature. This works so much better now!

**Comment by ryanfitzer** [comment]
Glad it's working out for you.

Regarding `TM_eslint_fix`, you can set that globally in one of two places:

  - Preferences > Variables
  - `~/.tm_properties`

**Comment by ryanfitzer** [comment]
One note: While testing on a project in a Dropbox directory, I found the auto fix to be an issue. For the live updates to work, I'm getting the contents of the file via `process.env.stdin`. It seems that when Dropbox is reconciling file changes to sync, it uses some sort of version control to diff the file. This resulted in diff characters showing up while editing the file.

Let me know if you see any similar issues. The turnaround for linting/fixing is ~750 milliseconds on my machine. This may prove to be too slow for the live linting feature. I'm thinking of adding an option to turn it off when in live linting mode. This way you can still use live linting, but only auto fix when the file is saved.

An another idea is to debounce the live updates until there's a lull in editing, but that may be too fiddly.

Let me know what you think.

**Comment by imakeinterfaces** [comment]
I don't mind the lag personally. I've been living with it for a while now. I also don't use dropbox to sync code so i'm not running into that problem.

 I have found that even with the delay, this bundle works better for me than a language server like the one in vscode. There was an extensive thread on leveraging the textmate events system to try to build langauge server integreation here http://textmate.1073791.n5.nabble.com/Language-Server-Protocol-LSP-td31826.html Maybe that's helpful but i admittedly have no first hand experience with this.

I occasionally use sublimetext and the linting plugin for that shows almost the exact same lint times and I don't think anyone has any complaints about lag with that package. The only problem i have noticed with the auto linting is that occasionally change marks get shown. I believe this is some kind of race condition with the autofixer (maybe hitting save twice too quickly?). My only other complaint is that live lint isn't enabled by default, and i switch between projects quite a bit. It would be nice to have a setting to force it to always be on. Thanks again for all of the work on this, i see the commit log was pretty significant.
